version: '3.1'
services:
  master:
    image: mysql:5.7.9
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - localhost

networks:
  localhost:
